<a href="https://colab.research.google.com/github/FrancescoCortopassi/copilot-codespaces-vscode/blob/main/LEZIONE_21.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**MODULO RANDOM per ARRAY:** Questa parte è molto importante in finanza perchè molot spesso le cose in finanza seguono un processo randomizzato

In [4]:
import numpy as np
random_array = np.random.rand (6)
random_array

array([0.934961  , 0.18801187, 0.12707673, 0.27371712, 0.10531623,
       0.98018995])

Come possiamo vedere Python ha creato una serie di numeri random in un array

In [12]:
ran = np.random.rand (5)
print (f"Shape is {np.shape(ran)}")

ran =ran.reshape(-1,1)
print (f"Shape is {np.shape(ran)}")

Shape is (5,)
Shape is (5, 1)


Si necessita un'approfondimento di questa parte dato che così esposta non è molto intuitiva come situazione

In [15]:
#Random con valori interi
arr_int =np.random.randint(0,100,10)
print (arr_int)

[ 5 41 27 28 73 32 57 15  6 99]


In [17]:
#Random con valori interi (scegliendo la size della tabella) esperimento 1
arr_int =np.random.randint(100,size=(5,5))
print (arr_int)

[[23 54 12 23 63]
 [43 74 72 46 27]
 [99  2 89 29 87]
 [92 19  0 82 63]
 [40 96 42 82 76]]


In [19]:
#Random con valori interi (scegliendo la size della tabella) esperimento 2
arr_int =np.random.randint(100,size=(5,30))
print (arr_int)

[[34 87 67 15 47 58 18 62 95 89 74 97 32 62 93 39 13 82 46 57 16 54 41 43
  47 60  9 33 55 76]
 [43 70  2 10 84 57 94 70 70 21 34 86 96 32 21 45 40 39 72 79 53 32  7  7
  16 17 40 97 17  8]
 [37 55  8 84 52 58 87 67 89 84 26 32  3 85 21 12 82 48 99 18 31 70 79 54
   0 40 85 37 48  4]
 [60 60  8 60 36 20 23 11  8 64 45 55 94 90 94 40 50 59  0 68 58 77 64 86
  23 57 88 95 35 53]
 [91 94 31 10 20  9 66 65 10 63 49 75  0  7 67 28 35 22 12 28  4 79 34 84
  78  5 49 85 79 67]]


In [32]:
#Normalizzazione a 2 dimensioni
np.random.normal (loc=0, scale= 0.1, size= (3,5))

array([[-0.12847215, -0.11607061, -0.10107731, -0.00575453,  0.02339423],
       [-0.19812415,  0.0550693 ,  0.10905536, -0.18236016, -0.05276592],
       [ 0.00130519, -0.0674394 ,  0.25534237,  0.09493196, -0.05145967]])

In [4]:
import numpy as np
print (np.random.seed(seed=43))
print (np.random.rand (6,6))

None
[[0.11505457 0.60906654 0.13339096 0.24058962 0.32713906 0.85913749]
 [0.66609021 0.54116221 0.02901382 0.7337483  0.39495002 0.80204712]
 [0.25442113 0.05688494 0.86664864 0.221029   0.40498945 0.31609647]
 [0.0766627  0.84322469 0.84893915 0.97146509 0.38537691 0.95448813]
 [0.44575836 0.66972465 0.08250005 0.89709858 0.2980035  0.26230482]
 [0.00512955 0.54320252 0.47559637 0.63637368 0.97820413 0.90866276]]


In [39]:
import numpy as np
dir (np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi