<a href="https://colab.research.google.com/github/FrancescoCortopassi/copilot-codespaces-vscode/blob/main/LEZIONE_20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#NUMPY: Questa è la libreria che ci permette di eseguire clacoli complessi in Python

In [6]:
#Importare Numpy
import numpy as np
np

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

In [7]:
#creaiamo un array ad una dimensione
array = np.array([1,2,3])
array

array([1, 2, 3])

In [8]:
#la funzione LINSPACE
np.linspace(0,50,51)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [13]:
np.linspace (0,20,21)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20.])

In [16]:
np.linspace (0,20,0.5)

array([ 10. ,  10.9,  11.8,  12.7,  13.6,  14.5,  15.4,  16.3,  17.2,
        18.1,  19. ,  19.9,  20.8,  21.7,  22.6,  23.5,  24.4,  25.3,
        26.2,  27.1,  28. ,  28.9,  29.8,  30.7,  31.6,  32.5,  33.4,
        34.3,  35.2,  36.1,  37. ,  37.9,  38.8,  39.7,  40.6,  41.5,
        42.4,  43.3,  44.2,  45.1,  46. ,  46.9,  47.8,  48.7,  49.6,
        50.5,  51.4,  52.3,  53.2,  54.1,  55. ,  55.9,  56.8,  57.7,
        58.6,  59.5,  60.4,  61.3,  62.2,  63.1,  64. ,  64.9,  65.8,
        66.7,  67.6,  68.5,  69.4,  70.3,  71.2,  72.1,  73. ,  73.9,
        74.8,  75.7,  76.6,  77.5,  78.4,  79.3,  80.2,  81.1,  82. ,
        82.9,  83.8,  84.7,  85.6,  86.5,  87.4,  88.3,  89.2,  90.1,
        91. ,  91.9,  92.8,  93.7,  94.6,  95.5,  96.4,  97.3,  98.2,
        99.1, 100. ])

In [21]:
#la funzione ARRANGE
np.arange (0,51)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [ ]:
#creare un array 2D
import numpy as np
arr_bis = numpy.array ([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
arr_bis

In [35]:
np.array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**NOTA:** GENERALMENTE GLI ARRAY NON SI CREANO MA SI IMPORTANO DIRETTAMENTE COME DATA-SET, per cui questa operatività non sarà usata generalmente ma solo nel caso che si voglia creare un dataset personalizzato

In [40]:
#NULL MATRIX ARRAY
o = np.zeros ([3,5])
o

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [41]:
#IDENTITY MATRIX
identity = np.identity (5)
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
#ONE MATRIX
one= np.ones ([3,5])
one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [48]:
#sommare due array
o + one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [49]:
#sottrarre due matrici
o - one

array([[-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.]])

In [50]:
#Moltiplicazione scalare / Scalar moltiplication
one * 10

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

**SINTASSI: **Ogni array deve essere inserito all'intterno di parentesi quadre, a loro volta inserite nelle parentesi tonde. ESEMPIO:
numeri_magliette= np.array ([1,5,60])